id: application
order: 1
title:
  de: Applikation
  fr: Application
  en: Application
items:
-
  id: 1
  title:
    de: Bohren
    en: Bohren
    fr: Bohren
  groups: [1]
  recommended: [3,8]
  available: [2,4,5]
-
  id: 2
  title:
    de: Reiben
    en: Reiben
    fr: Reiben
  groups: [1]
  recommended: [3,7,8]
  available: [2,4,5]
-
  id: 3
  title:
    de: Gewinden
    en: Gewinden
    fr: Gewinden
  groups: [1]
  recommended: [3,5,7]
  available: [1,2,4,9]
-
  id: 4
  title:
    de: Fräsen
    en: Fräsen
    fr: Fräsen
  groups: [1]
  recommended: [3,7,8]
  available: [2,4,5]
-
  id: 5
  title:
    de: Drehen
    en: Drehen
    fr: Drehen
  groups: [1]
  recommended: [3,7,8]
  available: [2,4,5]
-
  id: 6
  title:
    de: Verzahnen
    en: Verzahnen
    fr: Verzahnen
  groups: [1]
  recommended: [7]
  available: [2,3,4,5,8]
-
  id: 7
  title:
    de: Räumen
    en: Räumen
    fr: Räumen
  groups: [1]
  recommended: [3,7]
  available: [2,4,5,8]
-
  id: 8
  title:
    de: Sägen
    en: Sägen
    fr: Sägen
  groups: [1]
  recommended: [3,7]
  available: [2,4,5,8]
-
  id: 9
  title:
    de: Feinstanzen/Prägen
    en: Feinstanzen/Prägen
    fr: Feinstanzen/Prägen
  groups: [1]
  recommended: [3,5,7]
  available: [2,4]
-
  id: 10
  title:
    de: Walzprofilieren
    en: Walzprofilieren
    fr: Walzprofilieren
  groups: [1]
  recommended: [3,5,7]
  available: [2,4]
-
  id: 11
  title:
    de: Tiefziehen
    en: Tiefziehen
    fr: Tiefziehen
  groups: [1]
  recommended: [5,7,9]
  available: [2,3,4]
-
  id: 12
  title:
    de: Umformen
    en: Umformen
    fr: Umformen
  groups: [1]
  recommended: [5,7,9]
  available: [2,3,4]
-
  id: 13
  title:
    de: Warmumformen
    en: Warmumformen
    fr: Warmumformen
  groups: [1]
  recommended: [7]
  available: [4]
-
  id: 14
  title:
    de: Druckguss
    en: Druckguss
    fr: Druckguss
  groups: [1]
  recommended: []
  available: [5,7]
-
  id: 15
  title:
    de: Kunstoffspritzen
    en: Kunstoffspritzen
    fr: Kunstoffspritzen
  groups: [1]
  recommended: [3,7,9]
  available: [2]
