-
  id: 1
  title:
    de: Bohren
    en: Bohren
    fr: Bohren
  materials: [1, 2, 3, 4, 5]
-
  id: 2
  title:
    de: Reiben
    en: Reiben
    fr: Reiben
-
  id: 3
  title:
    de: Gewinden
    en: Gewinden
    fr: Gewinden
-
  id: 4
  title:
    de: Fräsen
    en: Fräsen
    fr: Fräsen
-
  id: 5
  title:
    de: Walzprofilieren
    en: Walzprofilieren
    fr: Walzprofilieren
-
  id: 6
  title:
    de: Drehen
    en: Drehen
    fr: Drehen
-
  id: 7
  title:
    de: Verzahnen
    en: Verzahnen
    fr: Verzahnen
-
  id: 8
  title:
    de: Räumen
    en: Räumen
    fr: Räumen
-
  id: 9
  title:
    de: Sägen
    en: Sägen
    fr: Sägen
-
  id: 10
  title:
    de: Spritz- und Druckgiessen
    en: Spritz- und Druckgiessen
    fr: Spritz- und Druckgiessen
-
  id: 11
  title:
    de: Feinstanzen/Prägen
    en: Feinstanzen/Prägen
    fr: Feinstanzen/Prägen
-
  id: 12
  title:
    de: Tiefziehen
    en: Tiefziehen
    fr: Tiefziehen
-
  id: 13
  title:
    de: Umformen
    en: Umformen
    fr: Umformen
-
  id: 14
  title:
    de: Warmumformen
    en: Warmumformen
    fr: Warmumformen
